### ISSUE TITLE
Suspend the application if another application is running in full screen mode

### ISSUE THREAD

**Issue by LisaJackson24-2** [LucaReggiannini/winycorners#1]
First of all, thank you for the program. The only significant drawback for me is that the hot corners work even if another application is running in full-screen mode. This is very problematic as it leads to to false positives, for example, during games. Hope you can fix this and provide a special option for it. If anything, you can take a look at this project, it is also in C#, there such an option is implemented, plus, there is support for multiple monitors, which would also be very useful for many.

https://github.com/RobertSmits/Windows-10-HotCorners

Wish you a good day.

Sincerely,
Lisa Jackson

**Comment by LucaReggiannini** [comment]
Thanks so much for your feedback! I didn't think anyone would find this tool useful. I will implement this feature soon

**Comment by LisaJackson24-2** [comment]
> Thanks so much for your feedback! I didn't think anyone would find this tool useful. I will implement this feature soon

Oh that's wonderful ☺️

**Comment by LucaReggiannini** [comment]
Hello. Please check my new release: https://github.com/LucaReggiannini/winycorners/releases/tag/v1.4.0
Tested with fullscreen videos and some Steam games.
Does it work for you?

Edit: published release 1.4.0 with a new fix for Windows 11

**Comment by LisaJackson24-2** [comment]
> Hello. Please check my new release: https://github.com/LucaReggiannini/winycorners/releases/tag/v1.4.0 Tested with fullscreen videos and some Steam games. Does it work for you?
> 
> Edit: published release 1.4.0 with a new fix for Windows 11

THX. The issue with full-screen programs has indeed been resolved, but now there's another problem. Now when hovering, Win+Tab mode is launched, but when hovering again, for some reason it does not close, does not work cyclically.

Additionally, the size of the zone itself seems too large to me. Ideally, it would be great if we could customize its size ourselves. In GNOME, there is a top panel, and the Activities button is positioned on the left specifically for the Win+Tab mode. If I'm not mistaken, even there activation zone is located almost in the corner there.

**Comment by LucaReggiannini** [comment]
I see the on hovering problem. Is caused by some update of Windows 11 (are you testing on this system or Win10?). I will fix it

Additionally: do you mean the size of the square that triggers the hotcorner?

Edit: with release 1.2 do you have the on hovering problem on win 11?

**Comment by LisaJackson24-2** [comment]
> I see the on hovering problem. Is caused by some update of Windows 11 (are you testing on this system or Win10?). I will fix it
> 
> Additionally: do you mean the size of the square that triggers the hotcorner?
> 
> Edit: with release 1.2 do you have the on hovering problem on win 11?

Yes, I'm using Windows 11.
Yes, exactly his. The response area is too large, many times when I clicked on the first tab in the browser, TaskView was randomly launched. Ideally, worth using the corner of 1*1 pixel.
In version 1.2 everything was fine.

**Comment by LucaReggiannini** [comment]
Thanks for the help. Fixes coming soon

**Comment by LucaReggiannini** [comment]
Take a look at https://github.com/LucaReggiannini/winycorners/releases/tag/v1.5.0

The Windows 11 task view is different from the Windows 10 task view and is considered a full screen application so the new check to prevent the hot corner trigger in full screen applications was preventing the tool from working properly when the task view was visible.  This problem has been fixed.

Plus i have added a `--corner-size` option. If you want an hot corner of 1px you can use:
```
winycorners.exe --top-left --enhanced-task-view --corner-size 1
```

Let me know if this work for you

**Comment by LisaJackson24-2** [comment]
> Take a look at https://github.com/LucaReggiannini/winycorners/releases/tag/v1.5.0
> 
> The Windows 11 task view is different from the Windows 10 task view and is considered a full screen application so the new check to prevent the hot corner trigger in full screen applications was preventing the tool from working properly when the task view was visible. This problem has been fixed.
> 
> Plus i have added a `--corner-size` option. If you want an hot corner of 1px you can use:
> 
> ```
> winycorners.exe --top-left --enhanced-task-view --corner-size 1
> ```
> 
> Let me know if this work for you

Still not working 😕

Also, it should be noted that the TaskView response is also not very fast in my opinion, if you also have it coded, it would not be bad to bring it out as a separate option as well

**Comment by LucaReggiannini** [comment]
Do you refer to the on mouse hover problem? Can I suggest to terminate every winycorner instance via task manager or taskkill and try again?

For the responsiveness I'm try to figure it out if there is something I can do. For me the task view has a little latency even if I hit win + tab keys

**Comment by LisaJackson24-2** [comment]
> 

Yes. I simply overwrite the exe files, accordingly, all instances are closed for me.

As for delay, I also didn't notice the slow response in version 1.2, maybe just because of incorrect operation, now it seems slower than the Win+Tab combination 🤷‍♂️

**Comment by LucaReggiannini** [comment]
Unfortunately I can't reproduce the problem. This is my current situation (tested on Windows 11 and 10):

https://github.com/LucaReggiannini/winycorners/assets/46603573/0d7f6896-6836-4ab1-a3d3-40ada9a82a30

Just in case something is different on your system I made a small utility called Fghelper (there is a precompiled binary: https://github.com/LucaReggiannini/winycorners/raw/main/fghelper.exe). 

On the readme of this repo I've added some instruction to make it work.

Can you please run the program, press `Win+Tab` and wait a couple of seconds just to see the Task View informations?

For example this is my output:

![Screenshot 2023-07-03 172122](https://github.com/LucaReggiannini/winycorners/assets/46603573/6a76d631-c7c1-4ef2-bdd7-c6457444cec7)


Btw I will soon add some options to make the tool a little bit faster.

**Comment by LucaReggiannini** [comment]
Hello @LisaJackson24-2 . I finished a new version of the program with major improvements.
Release link: https://github.com/LucaReggiannini/winycorners/releases/tag/v1.7.0

Changelog:
```
1. Added "--update-time" and "--enhanced-task-view-delay" options.
2. WinYcorners now tries to terminate other running instances of itself based on current process name
3. Now there is only one method (instead of two) to check for Task View visibility (compatible with both Windows 10/11)
4. Minor adjustment, optimizations and bugfixes
```

Now you se use "--update-time" and "--enhanced-task-view-delay" to reduce some latency (however I recommend the default values based on my system configuration). Plus I changed a lot of things in the code so it should work better (at least it does on my system). 

Any feedback is appreciated
